### ISSUE TITLE
Dialect support?

### ISSUE THREAD

**Issue by srl295** [tc39-transfer/proposal-intl-displaynames#20]
https://unicode.org/reports/tr35/tr35-general.html#Display_Name_Elements

example `nl-BE` = "Flemish", not just "Dutch (Belgium)"

**Comment by FrankYFTang** [comment]
@srl295  Just want to clarify, are you asking 
1) the implementation to output "Flemish" for "nl-BE" instead of  "Dutch (Belgium)", or 
2) the specification to allow the API to allow both "Flemish" and "Dutch (Belgium)" could be output for  "nl-BE" and demand a method to control which one being output?

The current draft of specification does not mandate the implementation to only output  "Dutch (Belgium)", the implementation could choose to output "Flemish". It does not give the API caller to control the output. But is such control necessary? Shouldn't the implementation always try to output "Flemish"?

**Comment by srl295** [comment]
@FrankYFTang coming back to this:
> is such control necessary? Shouldn't the implementation always try to output "Flemish"?

Yes, it's necessary. When choosing a language, it's common to sort the same language together:

- mac example
![image](https://user-images.githubusercontent.com/855219/81836404-447c0480-94f8-11ea-9dd8-336abd6f684f.png)

**Comment by srl295** [comment]
CLDR calls it CombineLanguage

**Comment by FrankYFTang** [comment]
Could you first clarify which one you are asking about?

1. the implementation to output "Flemish" for "nl-BE" instead of "Dutch (Belgium)", OR
2. the specification to allow the API to allow both "Flemish" and "Dutch (Belgium)" could be output for "nl-BE" and demand a method to control which one being output?

**Comment by srl295** [comment]
> Could you first clarify which one you are asking about?

Yes, sorry for my terseness.

> 1. the implementation to output "Flemish" for "nl-BE" instead of "Dutch (Belgium)", OR

(1) is already what the implementation provides, so I was not commenting on that.

> 2. the specification to allow the API to allow both "Flemish" and "Dutch (Belgium)" could be output for "nl-BE" and demand a method to control which one being output?

(2) is necessary for the reason mentioned above.  Language selection UIs need to be able to choose "Dutch (Belgium)".

**Comment by anba** [comment]
FWIW the SpiderMonkey implementation (currently only available through the shell-only `addIntlExtras` helper), defaults to `UDISPCTX_STANDARD_NAMES` per the recommendation voiced in <https://unicode-org.atlassian.net/browse/CLDR-13430>. So for `nl-BE`, SpiderMonkey returns `"Dutch (Belgium)"`.

**Comment by FrankYFTang** [comment]
I put together a v2 repo on https://github.com/FrankYFTang/intl-displaynames-v2/ please move the future discussion there.

**Comment by FrankYFTang** [comment]
This proposal reach Stage 4 in 2020 Sept TC39 meeting. Move this issue to https://github.com/tc39/intl-displaynames-v2/issues/13
